name: TheBridge
version: ${project.version}
main: gg.bridgesyndicate.bridgeteams.BridgeTeams
api-version: 1.8
authors: [bdamja, vice, ken]
depend: [ProtocolLib]
commands:
  shout:
    description: Send a message to all players
    usage: /<command> <message>