version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - echo Build started on `date`
      - mvn clean package -P package-all
artifacts:
  files:
    - NoThrow/target/NoThrow-1.0-SNAPSHOT.jar
    - ArrowRegen/target/ArrowRegen-1.0-SNAPSHOT.jar
  discard-paths: yes
