version: 0.2
phases:
  build:
    commands:
      - echo updating ecs service
      - aws ecs update-service --cluster SyndicateECSCluster --service arn:aws:ecs:us-west-2:595508394202:service/SyndicateECSCluster/SyndicateBridgeECSService --force-new-deployment
