name: BridgeRespawn
version: ${project.version}
main: gg.bridgesyndicate.bridgerespawn.BridgeRespawn
api-version: 1.8
authors: [ bdamja ]
description: Instantly respawns to the desired side when killed
