FROM 595508394202.dkr.ecr.us-west-2.amazonaws.com/syn-bridge-servers
WORKDIR /app/minecraft-home
RUN apt-get update && apt-get install -y patch
ADD scripts/no-bungee.server.properties.diff .
ADD scripts/no-bungee.spigot.yml.diff .
RUN patch -p1 < ./no-bungee.spigot.yml.diff
RUN patch -p1 < ./no-bungee.server.properties.diff
RUN mkdir sample-json
ADD sample-json/game.json sample-json/game.json
