FROM 595508394202.dkr.ecr.us-west-2.amazonaws.com/syn-bridge-servers
WORKDIR /app/minecraft-home
RUN sed -i -e's/online-mode=false/online-mode=true/' server.properties
RUN sed -i -e'/bungeecord: true/d' spigot.yml

